### ISSUE TITLE
not with windows :(

### ISSUE THREAD

**Issue by Zibri** [yume-chan/webrtc-tunnel#70]
Running the client on windows, port 1082 is correctly created and listening.
If I use curl --proxy socks5://127.0.0.1:1082 https://www.google.com   it WORKS.

But if I set the proxy in windows to use 127.0.0.1 port 1082   nothing works.

Can you please fixt this?

**Comment by yume-chan** [comment]
Windows only supports HTTP proxy. There are programs that can convert SOCK5 proxy into HTTP proxy, you can use them together.

**Comment by Zibri** [comment]
You mean the windows **version**.. because windows supports **any kind** of proxy 😃

**Comment by Zibri** [comment]
it's your mistake not windows mistake. I run other socks5 proxies on the same machine...
